### PR TITLE
chore: upgrade yargs to suppress mem advisory

### PR DESCRIPTION
**Pull request by stabback**
Fixes https://github.com/ngx-translate/i18n-polyfill/issues/65 to suppress https://www.npmjs.com/advisories/1084 on projects that use this package.

Upgrade [yargs](https://github.com/yargs/yargs) to the minimum version needed to suppress this error.  Breaking changes in yargs along the way:

10 => 11: https://github.com/yargs/yargs/blob/master/CHANGELOG.md#breaking-changes-1
11 => 12: https://github.com/yargs/yargs/blob/master/CHANGELOG.md#breaking-changes-2

I do not believe these impact this package, however this should be confirmed.

### CODE REVIEW

**Comment by greggbjensen** [comment]
This is an important update, can we get this added?

**Comment by ssj3sunny** [comment]
Will there be a release for this change?

**Comment by seemanski** [comment]
Are there plans to get this change published onto npmjs?

**Comment by jwmarshall** [comment]
Still waiting on a published version...

**Comment by timothyBrake** [comment]
Would be really great if someone published a version as it is a security risk and it is fixed already but no version in nom. Any ideas on how to cleanly incorporate this in our code until someone publishes an actual version?

**Comment by stabback** [comment]
@ocombe Thank you for merging this back in November.  Unfortunately, without a publish the community at large is still at risk and is confronted with audit failures.  Can a patch release be prioritized?

**Comment by wartab** [comment]
You guys need to stop acting like there is a risk. Read the description of this vulnerability and if you are a at risk, just because `@ngx-translate/i18n-polyfill` is installed in your projects, you are having bigger issues than this.

**Comment by timothyBrake** [comment]
Thank you @wartab for your free valuable professional security consulting feedback to resolve this specific issue. Your comment got this ticket closer to actually being finalized and a clean green slate security report that goes along with it that matters for some companies and lawyers, not matter what the view of a developer might be and how small a known security risk actually is. Nobody is stating 'bring down the app because of this issue' but are just asking to create an actual release version of an already merged fix.

**Pull request merged**
